#!/bin/bash


#
# Set up paths
# 

initial_directory=$(pwd)
file_in=$(readlink -f "$1")
file_out=$(readlink -f "$2")
file_out_basename=$(basename "$file_out")

#
# Set up the temporary storage
# 

tmpdir=$(mktemp -d)
cd $tmpdir

function cleanup() 
{
    rm -rf $tmpdir
    cd $initial_directory
}
trap "cleanup" EXIT # makes sure we clean up after ourselves

#
# Extract raw pages and text
#

ddjvu -format=tiff "$file_in" tmp_multipage.tiff
tiffsplit tmp_multipage.tiff tmp_page_
rm tmp_multipage.tiff
num_pages=$(djvused -e 'n' "$file_in")
strlen_num_pages="${#num_pages}"
i=0
for page_alpha in tmp_page_*; do
    i=$[i+1]
    j=$(printf "%0${strlen_num_pages}d" $i)
    mv $page_alpha tmp_page_${j}.tiff

    # OCR content needs to have one html file per page for `pdfbeads`;
    # `djvu2hocr` is capable of extracting it all at once, but then it
    # goes into one big file which we would need to split afterwards,
    # this would require html parsing, which is just too much.  The
    # s/ocrx/ocr/g substitution is a small hack to make `pdfbeads`
    # understand the output from `djvu2hocr`.

    djvu2hocr "$file_in" -p $i | sed 's/ocrx/ocr/g' > tmp_page_${j}.html
done


#
# Generate the TOC
#

djvused -e 'print-outline' "$file_in" > toc.txt

# The output returned by `djvused` has an s-expression like
# tree structure, which is incompatible with the indentation based
# structure used by `pdfbeads`

djvu2pdf_toc_parser.py < toc.txt > toc.out.txt


#
# Generate the final PDF
#
if compgen -G "tmp_page_*.tiff" > /dev/null; then
    page_pairs=()
    mapfile -t page_tiffs < <(printf '%s\n' tmp_page_*.tiff | sort)
    for tiff_file in "${page_tiffs[@]}"; do
        base_name="${tiff_file%.tiff}"
        html_file="${base_name}.html"
        if [[ ! -f "$html_file" ]]; then
            echo "Missing OCR HTML for page $tiff_file" >&2
            exit 1
        fi
        page_pairs+=("${tiff_file}" "${html_file}")
    done

    if ! pdfbeads --toc toc.out.txt -o output.pdf "${page_pairs[@]}"; then
        echo "pdfbeads failed to generate the final PDF" >&2
        exit 1
    fi
else
    echo "No page TIFF files were generated" >&2
    exit 1
fi
mv output.pdf "$file_out"
